"""hb compile --engine redis — Redis configuration generator.

Reads redis_patterns from the data dictionary and generates:
1. Redis CLI script (for manual setup / debugging)
2. JSON application config (for app-level cache layer)

6 supported use cases:
  - config_cache (HASH, write-through, TTL)
  - session_store (STRING, TTL)
  - notification_rt (PUBSUB)
  - chat_recent (LIST, max items, TTL)
  - rate_limiting (STRING, increment, TTL)
  - feature_flags (HASH, write-through, TTL)

PBI #550 — Feature #541.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

class RedisPattern(BaseModel):
    """A single Redis usage pattern from the dictionary."""
    use_case: str
    entity: str | None = None
    structure: str  # HASH, STRING, LIST, PUBSUB, SORTED_SET
    key: str  # Key pattern with placeholders
    ttl: int | None = None  # seconds
    strategy: str = "read-through"  # write-through, session, publish, increment
    max_items: int | None = None

    model_config = {"extra": "ignore"}


class RedisCompileResult(BaseModel):
    """Result of Redis compilation."""
    patterns: list[RedisPattern]
    cli_script: str = ""
    app_config: dict[str, Any] = Field(default_factory=dict)
    docs: str = ""


# ---------------------------------------------------------------------------
# Redis CLI script generator
# ---------------------------------------------------------------------------

def _gen_cli_script(patterns: list[RedisPattern]) -> str:
    """Generate a Redis CLI script with example commands for each pattern."""
    lines: list[str] = [
        "# =============================================================",
        "# Redis Configuration — Generated by hale-bopp-db compile",
        "# =============================================================",
        "",
    ]

    for p in patterns:
        lines.append(f"# --- {p.use_case} ---")
        lines.append(f"# Structure: {p.structure}")
        lines.append(f"# Key pattern: {p.key}")
        lines.append(f"# Strategy: {p.strategy}")
        if p.ttl:
            lines.append(f"# TTL: {p.ttl}s")
        if p.max_items:
            lines.append(f"# Max items: {p.max_items}")
        lines.append("")

        # Example commands based on structure type
        if p.structure == "HASH":
            lines.append(f"# Example: write")
            lines.append(f"# HSET {_example_key(p.key)} field1 value1 field2 value2")
            if p.ttl:
                lines.append(f"# EXPIRE {_example_key(p.key)} {p.ttl}")
            lines.append(f"# Example: read")
            lines.append(f"# HGETALL {_example_key(p.key)}")

        elif p.structure == "STRING":
            if p.strategy == "increment":
                lines.append(f"# Example: increment")
                lines.append(f"# INCR {_example_key(p.key)}")
                if p.ttl:
                    lines.append(f"# EXPIRE {_example_key(p.key)} {p.ttl}")
            else:
                lines.append(f"# Example: set")
                lines.append(f"# SET {_example_key(p.key)} <value>")
                if p.ttl:
                    lines.append(f"# Example: set with TTL")
                    lines.append(f"# SETEX {_example_key(p.key)} {p.ttl} <value>")

        elif p.structure == "LIST":
            lines.append(f"# Example: push (left)")
            lines.append(f"# LPUSH {_example_key(p.key)} <value>")
            if p.max_items:
                lines.append(f"# Trim to max {p.max_items} items")
                lines.append(f"# LTRIM {_example_key(p.key)} 0 {p.max_items - 1}")
            if p.ttl:
                lines.append(f"# EXPIRE {_example_key(p.key)} {p.ttl}")
            lines.append(f"# Example: read recent")
            lines.append(f"# LRANGE {_example_key(p.key)} 0 -1")

        elif p.structure == "PUBSUB":
            lines.append(f"# Example: publish")
            lines.append(f"# PUBLISH {_example_key(p.key)} <message>")
            lines.append(f"# Example: subscribe")
            lines.append(f"# SUBSCRIBE {_example_key(p.key)}")

        elif p.structure == "SORTED_SET":
            lines.append(f"# Example: add")
            lines.append(f"# ZADD {_example_key(p.key)} <score> <member>")
            lines.append(f"# Example: range")
            lines.append(f"# ZRANGEBYSCORE {_example_key(p.key)} -inf +inf")

        lines.append("")

    return "\n".join(lines)


def _example_key(pattern: str) -> str:
    """Replace placeholders with example values."""
    return (
        pattern
        .replace("{tenant_id}", "T001")
        .replace("{token}", "abc123")
        .replace("{conversation_id}", "conv_001")
        .replace("{agent_id}", "agent_01")
        .replace("{minute}", "202603251030")
    )


# ---------------------------------------------------------------------------
# JSON application config generator
# ---------------------------------------------------------------------------

def _gen_app_config(patterns: list[RedisPattern]) -> dict[str, Any]:
    """Generate a JSON config for application-level cache layer."""
    config: dict[str, Any] = {
        "version": "1",
        "generated_by": "hale-bopp-db",
        "patterns": {},
    }

    for p in patterns:
        entry: dict[str, Any] = {
            "structure": p.structure,
            "key_pattern": p.key,
            "strategy": p.strategy,
        }
        if p.ttl is not None:
            entry["ttl_seconds"] = p.ttl
        if p.max_items is not None:
            entry["max_items"] = p.max_items
        if p.entity:
            entry["source_entity"] = p.entity

        config["patterns"][p.use_case] = entry

    return config


# ---------------------------------------------------------------------------
# Documentation generator
# ---------------------------------------------------------------------------

def _gen_docs(patterns: list[RedisPattern]) -> str:
    """Generate markdown documentation for each Redis pattern."""
    lines: list[str] = [
        "# Redis Patterns — hale-bopp-db",
        "",
        f"Total patterns: {len(patterns)}",
        "",
    ]

    for p in patterns:
        lines.append(f"## {p.use_case}")
        lines.append("")
        if p.entity:
            lines.append(f"- **Source entity**: `{p.entity}`")
        lines.append(f"- **Structure**: `{p.structure}`")
        lines.append(f"- **Key pattern**: `{p.key}`")
        lines.append(f"- **Strategy**: {p.strategy}")
        if p.ttl is not None:
            ttl_human = _ttl_human(p.ttl)
            lines.append(f"- **TTL**: {p.ttl}s ({ttl_human})")
        else:
            lines.append(f"- **TTL**: none (persistent or ephemeral)")
        if p.max_items is not None:
            lines.append(f"- **Max items**: {p.max_items}")
        lines.append("")

    return "\n".join(lines)


def _ttl_human(seconds: int) -> str:
    """Convert seconds to human-readable."""
    if seconds >= 3600:
        return f"{seconds // 3600}h"
    if seconds >= 60:
        return f"{seconds // 60}min"
    return f"{seconds}s"


# ---------------------------------------------------------------------------
# Main compiler
# ---------------------------------------------------------------------------

def compile_redis(
    redis_patterns: list[dict[str, Any]],
) -> RedisCompileResult:
    """Compile redis_patterns from the data dictionary."""
    patterns = [RedisPattern.model_validate(p) for p in redis_patterns]

    return RedisCompileResult(
        patterns=patterns,
        cli_script=_gen_cli_script(patterns),
        app_config=_gen_app_config(patterns),
        docs=_gen_docs(patterns),
    )


def compile_redis_and_write(
    redis_patterns: list[dict[str, Any]],
    output_dir: str | Path,
) -> RedisCompileResult:
    """Compile and write Redis config files to disk."""
    result = compile_redis(redis_patterns)

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    import json
    # CLI script
    (out / "redis-setup.sh").write_text(result.cli_script, encoding="utf-8")
    # App config JSON
    (out / "redis-config.json").write_text(
        json.dumps(result.app_config, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    # Documentation
    (out / "redis-patterns.md").write_text(result.docs, encoding="utf-8")

    return result
