"""hb compile security — Security DDL generator (3 profiles).

The differentiator: no competitor does security profiles → DDL.

Profiles:
  - essential:  audit + constraints + FK (no extra security DDL)
  - standard:   + RLS (tenant isolation) + PII tagging (COMMENT ON)
  - enterprise: + dynamic masking (views) + retention policy

Phase 1: PostgreSQL (PBI #544).
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from app.core.compile import DataDictionary, EntityDef


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

class SecurityDDL(BaseModel):
    """Result of security DDL generation."""
    profile: str
    engine: str
    rls_statements: list[str] = Field(default_factory=list)
    rls_setup: list[str] = Field(default_factory=list)
    pii_comments: list[str] = Field(default_factory=list)
    masking_statements: list[str] = Field(default_factory=list)
    retention_statements: list[str] = Field(default_factory=list)

    @property
    def has_content(self) -> bool:
        return bool(
            self.rls_statements or self.rls_setup or self.pii_comments
            or self.masking_statements or self.retention_statements
        )

    def to_files(self) -> list[dict[str, str]]:
        """Convert to numbered SQL files."""
        files: list[dict[str, str]] = []

        if self.rls_setup or self.rls_statements:
            parts = []
            if self.rls_setup:
                parts.append("-- RLS setup (enable, session variable)\n")
                parts.extend(self.rls_setup)
                parts.append("")
            if self.rls_statements:
                parts.append("-- RLS policies (tenant isolation)\n")
                parts.extend(self.rls_statements)
            files.append({
                "name": "006_rls.sql",
                "content": _header("Row-Level Security") + "\n".join(parts) + "\n",
            })

        if self.pii_comments:
            files.append({
                "name": "007_pii_tagging.sql",
                "content": _header("PII Tagging") + "\n".join(self.pii_comments) + "\n",
            })

        if self.masking_statements:
            files.append({
                "name": "008_masking.sql",
                "content": _header("Dynamic Data Masking") + "\n".join(self.masking_statements) + "\n",
            })

        if self.retention_statements:
            files.append({
                "name": "009_retention.sql",
                "content": _header("Data Retention") + "\n".join(self.retention_statements) + "\n",
            })

        return files


def _header(section: str) -> str:
    return (
        f"-- =============================================================\n"
        f"-- {section}\n"
        f"-- Generated by hale-bopp-db compile (Security DDL)\n"
        f"-- =============================================================\n\n"
    )


# ---------------------------------------------------------------------------
# Profile capabilities
# ---------------------------------------------------------------------------

def _get_capabilities(dictionary: DataDictionary, profile: str) -> dict[str, bool]:
    """Get capability flags for a security profile."""
    profiles = dictionary.security_profiles
    if profile in profiles:
        return profiles[profile].get("capabilities", {})
    # Hardcoded fallback
    defaults = {
        "essential": {"rls": False, "pii_tagging": False, "dynamic_masking": False, "retention_policy": False},
        "standard": {"rls": True, "pii_tagging": True, "dynamic_masking": False, "retention_policy": False},
        "enterprise": {"rls": True, "pii_tagging": True, "dynamic_masking": True, "retention_policy": True},
    }
    return defaults.get(profile, defaults["essential"])


# ---------------------------------------------------------------------------
# PostgreSQL Security DDL
# ---------------------------------------------------------------------------

def generate_security_pg(
    dictionary: DataDictionary,
    profile: str = "essential",
    schema_filter: str | None = None,
) -> SecurityDDL:
    """Generate PostgreSQL security DDL for the given profile."""
    caps = _get_capabilities(dictionary, profile)
    result = SecurityDDL(profile=profile, engine="pg")

    entities = dictionary.entities
    if schema_filter:
        entities = [e for e in entities if e.schema_name == schema_filter]

    if caps.get("rls"):
        _generate_rls_pg(entities, dictionary, result)

    if caps.get("pii_tagging"):
        _generate_pii_tags(entities, result)

    if caps.get("dynamic_masking"):
        _generate_masking_pg(entities, dictionary, result)

    if caps.get("retention_policy"):
        _generate_retention_pg(entities, result)

    return result


def _generate_rls_pg(
    entities: list[EntityDef],
    dictionary: DataDictionary,
    result: SecurityDDL,
) -> None:
    """Generate RLS policies for PostgreSQL (CREATE POLICY)."""
    rls_config = dictionary.raw_rls_map.get("pg", {}) if hasattr(dictionary, "raw_rls_map") else {}
    session_var = "current_setting('app.tenant_id', TRUE)"

    # RLS setup: enable RLS on tables that need it
    rls_tables: list[tuple[str, str]] = []  # (schema, table)

    for entity in entities:
        security = entity.security
        needs_rls = security.get("rls", False)
        # Also check multi_tenant — if True and has tenant_id, needs RLS
        if not needs_rls and entity.multi_tenant is True:
            has_tenant = any(c.name == "tenant_id" for c in entity.columns)
            if has_tenant:
                needs_rls = True

        if not needs_rls:
            continue

        # Verify entity actually has tenant_id column
        has_tenant_col = any(c.name == "tenant_id" for c in entity.columns)
        if not has_tenant_col:
            continue

        schema = entity.schema_name
        table = entity.name
        qualified = f"{schema}.{table}"
        rls_tables.append((schema, table))

        # Enable RLS on table
        result.rls_setup.append(f"ALTER TABLE {qualified} ENABLE ROW LEVEL SECURITY;")
        result.rls_setup.append(f"ALTER TABLE {qualified} FORCE ROW LEVEL SECURITY;")

        # Create policy
        policy_name = security.get("rls_policy", f"rls_tenant_{table}")
        result.rls_statements.append(
            f"DO $$ BEGIN\n"
            f"  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = '{table}' "
            f"AND schemaname = '{schema}' AND policyname = '{policy_name}') THEN\n"
            f"    CREATE POLICY {policy_name} ON {qualified}\n"
            f"      USING (tenant_id = {session_var});\n"
            f"  END IF;\n"
            f"END $$;"
        )


def _generate_pii_tags(
    entities: list[EntityDef],
    result: SecurityDDL,
) -> None:
    """Generate COMMENT ON for PII columns (Standard+)."""
    for entity in entities:
        security = entity.security
        pii_cols: set[str] = set()

        # From security.pii_columns
        for col_name in security.get("pii_columns", []):
            pii_cols.add(col_name)

        # From column-level pii flag
        for col in entity.columns:
            if col.pii:
                pii_cols.add(col.name)

        qualified = f"{entity.schema_name}.{entity.name}"
        for col_name in sorted(pii_cols):
            # Determine masking type if configured
            masking = security.get("masking", {})
            mask_type = masking.get(col_name, "unspecified")
            result.pii_comments.append(
                f"COMMENT ON COLUMN {qualified}.{col_name} IS "
                f"'PII: true | masking: {mask_type} | "
                f"Colonna contenente dati personali identificabili.';"
            )


def _generate_masking_pg(
    entities: list[EntityDef],
    dictionary: DataDictionary,
    result: SecurityDDL,
) -> None:
    """Generate masking views for PostgreSQL (Enterprise).

    PG doesn't have native Dynamic Data Masking like MSSQL,
    so we use view-based masking.
    """
    for entity in entities:
        security = entity.security
        masking_config = security.get("masking", {})
        if not masking_config:
            continue

        schema = entity.schema_name
        table = entity.name
        qualified = f"{schema}.{table}"

        # Build SELECT with masked columns
        select_parts: list[str] = []
        has_masked = False

        for col in entity.columns:
            if col.name in masking_config:
                has_masked = True
                mask_type = masking_config[col.name]
                if mask_type == "full":
                    select_parts.append(
                        f"    CASE WHEN current_setting('app.role', TRUE) = 'admin' "
                        f"THEN {col.name} ELSE '***' END AS {col.name}"
                    )
                elif mask_type == "partial":
                    # For email: show domain, mask local part
                    if "email" in col.name.lower():
                        select_parts.append(
                            f"    CASE WHEN current_setting('app.role', TRUE) = 'admin' "
                            f"THEN {col.name} ELSE "
                            f"CONCAT('***@', SPLIT_PART({col.name}, '@', 2)) END AS {col.name}"
                        )
                    else:
                        select_parts.append(
                            f"    CASE WHEN current_setting('app.role', TRUE) = 'admin' "
                            f"THEN {col.name} ELSE "
                            f"CONCAT(LEFT({col.name}, 1), '***') END AS {col.name}"
                        )
                else:
                    select_parts.append(f"    {col.name}")
            else:
                select_parts.append(f"    {col.name}")

        if not has_masked:
            continue

        view_name = f"{schema}.v_{table}_masked"
        select_block = ",\n".join(select_parts)

        result.masking_statements.append(
            f"CREATE OR REPLACE VIEW {view_name} AS\n"
            f"SELECT\n"
            f"{select_block}\n"
            f"FROM {qualified};"
        )
        result.masking_statements.append(
            f"COMMENT ON VIEW {view_name} IS "
            f"'Masked view for {table} — PII columns redacted for non-admin roles.';"
        )


def _generate_retention_pg(
    entities: list[EntityDef],
    result: SecurityDDL,
) -> None:
    """Generate retention policy DDL for PostgreSQL (Enterprise).

    Creates a reusable function + per-table retention config.
    """
    # Collect entities with retention config
    retention_entities: list[tuple[EntityDef, dict]] = []
    for entity in entities:
        retention = getattr(entity, "retention", None)
        if retention is None and hasattr(entity, "model_extra"):
            pass
        # Check in the raw security or entity-level
        # Retention is at entity level in the dictionary as a separate key
        # We'll check via model_extra or just skip if not present
        # For now, we look for it in the entity's model fields
        pass

    # Since retention is not in our Pydantic model yet, we generate
    # a generic retention function that can be configured per table
    result.retention_statements.append(
        "-- Retention function: delete rows older than N days from timestamped tables\n"
        "CREATE OR REPLACE FUNCTION hb_apply_retention(\n"
        "    p_schema TEXT,\n"
        "    p_table TEXT,\n"
        "    p_timestamp_col TEXT DEFAULT 'created_at',\n"
        "    p_retention_days INTEGER DEFAULT 365\n"
        ") RETURNS BIGINT\n"
        "LANGUAGE plpgsql AS $$\n"
        "DECLARE\n"
        "    v_deleted BIGINT;\n"
        "BEGIN\n"
        "    EXECUTE format(\n"
        "        'DELETE FROM %I.%I WHERE %I < NOW() - make_interval(days => %s)',\n"
        "        p_schema, p_table, p_timestamp_col, p_retention_days\n"
        "    );\n"
        "    GET DIAGNOSTICS v_deleted = ROW_COUNT;\n"
        "    -- Audit log\n"
        "    INSERT INTO observability.stats_execution_log (execution_id, proc_name, status, rows_deleted, start_time)\n"
        "    VALUES (gen_random_uuid()::TEXT, format('retention:%I.%I', p_schema, p_table), 'OK', v_deleted, NOW());\n"
        "    RETURN v_deleted;\n"
        "END;\n"
        "$$;"
    )

    # Generate retention calls for known LOG-type entities
    for entity in entities:
        if entity.type in ("LOG", "FACT"):
            # Check if entity has a timestamp column
            ts_col = None
            for col in entity.columns:
                if col.name in ("event_time", "created_at", "start_time"):
                    ts_col = col.name
                    break
            if ts_col:
                qualified = f"{entity.schema_name}.{entity.name}"
                result.retention_statements.append(
                    f"-- Retention for {qualified}: call hb_apply_retention('{entity.schema_name}', "
                    f"'{entity.name}', '{ts_col}', 365);"
                )
